# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Makes a public distribution."
  lane :distribute do
    carthage(
      command: "build",
      platform: "iOS",
      no_skip_current: true)

    carthage(
      command: "archive",
      frameworks: ["ScanditScanPlugin"],
      output: "SonectScanditScanPlugin.framework.zip")

    zip(
      path: "Carthage/Build/iOS/ScanditScanPlugin.framework",
      output_path: "SonectScanditScanPlugin_Cocoapods.framework.zip"
    )

    version = get_version_number(
      target: "ScanditScanPlugin")

    name = "Release " + version
    token = File.read("github.token")

    set_github_release(
      tag_name: version,
      name: name,
      description: "No changelog provided",
      repository_name: "sonect/sonect-scandit-scan-plugin",
      api_token: token,
      upload_assets: ["SonectScanditScanPlugin.framework.zip", "SonectScanditScanPlugin_Cocoapods.framework.zip"])

    commitAndPush("Update latest User Public build")
  
  end

  def commitAndPush(message) 
    git_add
    git_commit(path: "*", message: message)
    push_to_git_remote(
      local_branch: "master",
      remote_branch: "master")
  end

end
